### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by crylingya** [hxwork/OMNet_Pytorch#4] opened 2022-04-11 15:29 UTC
Thank you for your excellent work and code in Pytorch!

I have changed "train_batch_size": 4,"eval_batch_size": 64. But still get the runtime error whether training or testing the network. My computer's Graphics is GeForce RTX 2080 Ti/PCIe/SSE2.

I found that I always stopped at 'Loaded 1146 test instances.'. I have tried to use train_bs & eval_bs =4,8,16. I don't know why.

Could you give me some suggestions?

Here's the train_log:
2022-04-11 17:18:52,157 - Output and logs will be saved to ./experiments/ba/train.log
2022-04-11 17:18:52,174 - Using GPU ids: [0, 1]
2022-04-11 17:18:52,174 - Dataset type: modelnet_os, transform type: modelnet_os_prnet_clean
2022-04-11 17:18:52,175 - Train transforms: SplitSourceRef, ShufflePoints, PRNetTorch
2022-04-11 17:18:52,175 - Val and Test transforms: SetDeterministic, SplitSourceRef, ShufflePoints, PRNetTorch
2022-04-11 17:18:52,175 - Loading data from ./dataset/data/modelnet_os/modelnet_os_train.pickle for train
2022-04-11 17:18:52,175 - Categories used: [0, 1, 2, 3, 4, 7, 8, 11, 12, 13, 14, 16, 17, 18].
2022-04-11 17:18:52,176 - Loaded 4194 train instances.
2022-04-11 17:18:52,176 - Loading data from ./dataset/data/modelnet_os/modelnet_os_val.pickle for val
2022-04-11 17:18:52,176 - Categories used: [0, 1, 2, 3, 4, 7, 8, 11, 12, 13, 14, 16, 17, 18].
2022-04-11 17:18:52,177 - Loaded 1002 val instances.
2022-04-11 17:18:52,177 - Loading data from ./dataset/data/modelnet_os/modelnet_os_test.pickle for test
2022-04-11 17:18:52,177 - Categories used: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 38, 39].
2022-04-11 17:18:52,177 - Loaded 1146 test instances.

**Comment by hxwork** [comment] 2022-04-20 09:48
Hi,

Could you please provide more information or log about that error?

**Comment by crylingya** [comment] 2022-04-25 12:01
Here's the log for training:
2022-04-11 16:36:43,744 - Output and logs will be saved to ./experiments/experiment_omnet/train.log
2022-04-11 16:36:43,751 - Using GPU ids: [0, 1]
2022-04-11 16:36:43,752 - Dataset type: modelnet_os, transform type: modelnet_os_prnet_clean
2022-04-11 16:36:43,752 - Train transforms: SplitSourceRef, ShufflePoints, PRNetTorch
2022-04-11 16:36:43,752 - Val and Test transforms: SetDeterministic, SplitSourceRef, ShufflePoints, PRNetTorch
2022-04-11 16:36:43,752 - Loading data from ./dataset/data/modelnet_os/modelnet_os_train.pickle for train
2022-04-11 16:36:43,752 - Categories used: [0, 1, 2, 3, 4, 7, 8, 11, 12, 13, 14, 16, 17, 18].
2022-04-11 16:36:43,753 - Loaded 4194 train instances.
2022-04-11 16:36:43,753 - Loading data from ./dataset/data/modelnet_os/modelnet_os_val.pickle for val
2022-04-11 16:36:43,753 - Categories used: [0, 1, 2, 3, 4, 7, 8, 11, 12, 13, 14, 16, 17, 18].
2022-04-11 16:36:43,753 - Loaded 1002 val instances.
2022-04-11 16:36:43,753 - Loading data from ./dataset/data/modelnet_os/modelnet_os_test.pickle for test
2022-04-11 16:36:43,753 - Categories used: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 38, 39].
2022-04-11 16:36:43,753 - Loaded 1146 test instances.

Here's the log for testing
2022-04-19 13:57:43,125 - Output and logs will be saved to ./experiments/experiment_omnet/evaluate.log
2022-04-19 13:57:43,135 - Using GPU ids: [0, 1]
2022-04-19 13:57:43,136 - Dataset type: modelnet_os, transform type: modelnet_os_prnet_clean
2022-04-19 13:57:43,136 - Train transforms: SplitSourceRef, ShufflePoints, PRNetTorch
2022-04-19 13:57:43,136 - Val and Test transforms: SetDeterministic, SplitSourceRef, ShufflePoints, PRNetTorch
2022-04-19 13:57:43,137 - Loading data from ./dataset/data/modelnet_os/modelnet_os_train.pickle for train
2022-04-19 13:57:43,137 - Categories used: [0, 1, 2, 3, 4, 7, 8, 11, 12, 13, 14, 16, 17, 18].
2022-04-19 13:57:43,138 - Loaded 4194 train instances.
2022-04-19 13:57:43,138 - Loading data from ./dataset/data/modelnet_os/modelnet_os_val.pickle for val
2022-04-19 13:57:43,138 - Categories used: [0, 1, 2, 3, 4, 7, 8, 11, 12, 13, 14, 16, 17, 18].
2022-04-19 13:57:43,138 - Loaded 1002 val instances.
2022-04-19 13:57:43,138 - Loading data from ./dataset/data/modelnet_os/modelnet_os_test.pickle for test
2022-04-19 13:57:43,138 - Categories used: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 35, 36, 38, 39].
2022-04-19 13:57:43,138 - Loaded 1146 test instances.

I don't think I ever actually enterred the network. It seems that every time, I stopped after loading instances. I don't know why.

**Comment by crylingya** [comment] 2022-04-25 12:03
> Hi,
> 
> Could you please provide more information or log about that error?

Could you help me check what's wrong with my logs? Thanks a lot!

**Comment by hxwork** [comment] 2022-05-19 12:11
Hi,

Sorry about the late reply. I think there is no error appearing in your log. I am not sure if this problem is caused by the memory requirement.

**Comment by hxwork** [comment] 2022-06-08 06:06
Close it since there is no update.

**Closed as completed by hxwork** 2022-06-08 06:06 UTC
